---
title: "SECOND ASSIGNMENT"
author: "Aldo Giovanni e Giacomo"
date: "2023-06-02"
output: html_document
---

## EXERCISE 2- WE NEED SOME MUSIC!

## Description of the variables and exploratory analysis

Considering the data saved in spot.RDS, a description of the variables can be found on Kaggle:
- Acousticness: a confidence measure from 0.0 to 1.0 of whether the track is      acoustic. 1.0 represents high confidence the track is acoustic.
- Danceability: danceability describes how suitable a track is for dancing based   on a combination of musical elements including tempo, rhythm stability, beat    strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is   most danceable.
- Duration_ms: the track length in milliseconds.
- Energy:energy is a measure from 0.0 to 1.0 and represents a perceptual measure   of intensity and activity. Typically, energetic tracks feel fast, loud, and     noisy. 
- Explicit: whether or not the track has explicit lyrics (true = yes it does;     false = no it does not OR unknown)
- id: the Spotify ID for the track.
- Instrumentalness: predicts whether a track contains no vocals. "Ooh" and "aah"   sounds are treated as instrumental in this context. Rap or spoken word tracks   are clearly "vocal". The closer the instrumentalness value is to 1.0, the       greater likelihood the track contains no vocal content.
- Liveness: detects the presence of an audience in the recording. Higher          liveness values represent an increased probability that the track was           performed live. A value above 0.8 provides strong likelihood that the track is   live.
- Loudness: the overall loudness of a track in decibels (dB).
- Name:name of the track.
- Popularity: the popularity of a track is a value between 0 and 100, with 100    being the most popular. The popularity is calculated by algorithm and is        based, in the most part, on the total number of plays the track has had and     how recent those plays are. Generally speaking, songs that are being played a   lotnow will have a higher popularity than songs that were played a lot in the   past. Duplicate tracks (e.g. the same track from a single and an album) are     rated independently. Artist and album popularity is derived mathematically      from track popularity.
- Release_date of the song
- Speechiness: speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value.Values below 0.33 most likely represent music and other non-speech-like tracks.
- Tempo:the overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.
- Valence: a measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).
- First_auth: first author of the song.
- n: number of song for each artist.
- pop: variable containing the original column popularity rescaled between 0 and 1.

```{r}
library(boot)
library(tidyverse)
songs <- readRDS("spot (1).RDS")
head(songs)
boxplot(popularity~first_auth,data=songs)
```


